### ISSUE TITLE
FEATURE: Name on Commons Page

### ISSUE THREAD

**Issue by dscpsyl** [ucsb-cs156-m23/proj-happycows-m23-10am-4#19]
## User Story
After this change I will:
- see my name displayed on the commons page.

## Screenshots

This is what it currently looks like:
<img width="1366" alt="Screenshot 2023-08-11 at 1 22 07 AM" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/41165204/25ad19d8-4837-478e-9603-0c1cfd43fa6d">

And this is what it should be:
<img width="1335" alt="Screenshot 2023-08-11 at 1 22 25 AM" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/41165204/d08a4bda-5d58-4f4b-9cdd-33d6710dea85">

## Discussion
Why is our name only on the play page? We obviously have the data for it, and we can personalize the commons page with the name. It's a simple add, and it imminently greets the student.

**Comment by Elham-EN** [comment]
Hi @dscpsyl, can you assign me to this issue please.
