### ISSUE TITLE
EPIC: Auto Update Market Values Daily

### ISSUE THREAD

**Issue by dscpsyl** [ucsb-cs156-m23/proj-happycows-m23-10am-4#24]
## User Story
After this feature, I will:
- have market values be determined automatically

## Discussion
I noticed that commons can have a set market value. However, that's a little boring. I think it would be better to have it updated based on a random seed plus the current common conditions. This can help reflect real word markets and capitalism. How would we go about doing it? I have no idea. But just food for thought, and we could get around to it if possible?

**Comment by publicqi** [comment]
This is a good one. I might look into this.

**Comment by publicqi** [comment]
A better one: instead of daily a realtime market.

**Comment by dscpsyl** [comment]
Talked with team. Won't fix on this iteration.
