### ISSUE TITLE
FEATURE: MVP issues for Chat Backend

### ISSUE THREAD

**Issue by iain801** [ucsb-cs156-m23/proj-happycows-m23-10am-4#46]
# Feature Summary 

The aim is to have a chat box on the user commons page so that admin and users can send messages between each other.

This issue targets the CRUD backend for the basic commons chat feature.

# Discussion

This is a big feature, so it should be broken up into multiple issues; the list below is one suggestion.

Remember "minimum viable product"; the first iteration of this would be a single chat room for each Commons, without DM features; just a global chat where everyone sees everything.   

The list below mentions "hiding" messages (rather than deleting them).  That's not part of MVP, so make sure that all of the MVP features get done first.  However, I do suggest including the `private boolean hidden;` field in the entity even in the first iteration; database changes later are much more disruptive (since we don't have a good database migration strategy yet), so it's better to include all of the fields you might need in the initial run.

To that end, we might also include these fields in the entity:

`private boolean dm;`
`private Long toUserId`

The `dm` field would initially always be false, and the toUserId field would be `null`; we'll use those fields later when/if we implement DMs (but that will be a separate Epic.)

##  CRUD backend for messages MVP

- [x] There is an entity/repository for a ChatMessage.  A ChatMessage should have an id, userId, commonsId and a message payload.   You can use the `@CreationTimestamp` technique to automatically get a timestamp on the message. 
- [x] Include these fields for future use:
       `private boolean hidden;`
       `private Long toUserId`
- [x] The entity/repository for a ChatMessage should also have a "hidden" field that is initially false.  (This is because rather than deleting messages, we want to just "mark them as hidden".   This is to prevent users from using the chat to harass other users by sending inappropriate messages and then deleting them; messages marked as hidden remain in the database (so that they can be retained as evidence) but are not shown.   
- [x] There is a backend POST endpoint `/api/chat/post` where any user can create a message for a particular commonsId, provided they are a member of that commons.  If they have not joined that commons, that should be a 403 error.  The `hidden` field is initially `false`.   The endpoint should take these parameters: `commonsId` and `content`.   The userId should be determined automatically from the currentUser service on the backend, and should not be passed as a parameter. The `dm` field should always be set to `false` right now, and the `toUserId` set to null.
- [x] There is a backend endpoint `/api/chat/get` that takes a commonsId as a param, for retrieving chat messages for a particular commons that operates similar to the backend endpoint for jobs, in that it is paged, and sorted.   The endpoint should retrieve the most recent messages first, and should exclude any "hidden" messages.  It should retrieve messages for a particular commons only if the user is a member of that commons, or the user is an admin, otherwise it should return a 403

**Comment by dscpsyl** [comment]
- [x] Test for Controller `ChatMessageController.java`

**Comment by dscpsyl** [comment]
As of [d54586d](https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/commit/d54586db144718a58e636e6c1ae2ba5bbce723d3), the basic units are in place. Currently debugging issues with the queries in the repository (Springboot doesn't like them).

**Comment by dscpsyl** [comment]
As of [1afbd9f](https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/commit/1afbd9f9a4c625fb7d9216c46228c86b19c9b620), the repository is now passing the springboot compile phase. Next is creating a unit test for the controller and then manually testing the repository using swagger.

**Comment by dscpsyl** [comment]
As of [0f3b314](https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/commit/0f3b31483b1e96f8ec513e769fb02b2b4f848e9d),unit tests for the controller are now working. I will be manually testing the endpoints to check the repository functions on QA with swagger. If everything goes well. There should be a pull request for this by tonight.

**Comment by dscpsyl** [comment]
Currently getting 500 internal server errors for the get methods. That means the repositories are not working as expected. This will be the last fix and the backend will be ready
