### ISSUE TITLE
BUG: frontend jobs check does not render error message

### ISSUE THREAD

**Issue by publicqi** [ucsb-cs156-m23/proj-happycows-m23-10am-4#52]
# Summary
Frontend jobs checks does not render error message.

# Expected behavior
When the submit button is clicked on invalid inputs, the front end should render the error message.

# Current / Observed Behavior
Nothing is shown and no request is sent (this is wanted, because we don't want to post bad requests).

# Steps to Reproduce
1. Goto https://happycows-qa.dokku-07.cs.ucsb.edu/admin/jobs
2. For example, for `Set Cow Health for a Specific Commons`, use 1000 as the input and click on submit

**Comment by dscpsyl** [comment]
Closed due to time constraints. Should be looked into by future teams
