### ISSUE TITLE
REFACTOR: standardize precision used for storing data

### ISSUE THREAD

**Issue by publicqi** [ucsb-cs156-m23/proj-happycows-m23-10am-4#54]
Currently, many properties are using double. One drawback is that the precision is not user/frontend friendly.

For example,
<img width="1058" alt="image" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/56060664/6759e648-c0bd-4a89-9556-0a1aaaef7cfc">

Also, right now an admin can, for example, set the cow's health to an extremely small value like 1.0E-15.

Round it can be the trivial solution, but maybe come up with a better one.

**Comment by dscpsyl** [comment]
Where do we want to set number boundaries? In the user input or during calculation? This affects issues across the project and not just in frontend.

**Comment by pconrad** [comment]
So for the total wealth field, the problem is already solved (I think) via #2 

Is there another aspect to this problem that I'm not seeing?  For the moment, I don't understand what the issue is.

**Comment by publicqi** [comment]
An example is that I can set cow health to 1e-14.

<img width="1265" alt="image" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/56060664/0e8248f7-3ba6-4c15-9380-30668778cf34">

If we simply round the double, it would be zero'd like this Farm Stats panel.
<img width="441" alt="image" src="https://github.com/ucsb-cs156-m23/proj-happycows-m23-10am-4/assets/56060664/4fa95c4f-3eb6-4e25-9d8e-3cf436396d28">

Despite the explicit setting a value, an indirect way is the degradation rate.

**Comment by dscpsyl** [comment]
I think the most basic way to avoid this issue is to just choose an arbitrary precision value and stick with it. Eg. everything is rounded to 5 decimal places in the back end

**Comment by dscpsyl** [comment]
Closed due to time constraints. However, still something to think about as an edge case if precision requirements are added to the game in the future.
