### ISSUE TITLE
Rename Backend Folder and dependencies

### ISSUE THREAD

**Issue by dscpsyl** [ucsb-cs156-m23/proj-happycows-m23-10am-4#60]
Currently the java package imports are still at happiercow. Lets change this to happycow to be consistent

**Comment by sindhunaydu** [comment]
Hi @dscpsyl, I would really like to work on this issue, can you assign it to me? thanks!

**Comment by sindhunaydu** [comment]
Apart from renaming the `edu.ucsb.cs156.happiercows` package to `edu.ucsb.cs156.happycows`, should the following also be renamed, 
-  `HappierCowsApplication` to `HappyCowsApplication`
- `HappierCowsControllerAdvice` to `HappyCowsControllerAdvice`

**Comment by dscpsyl** [comment]
Removed due to logistics during this legacy timeframe. In order for this to happen smoothly, we would need to have no PR in queue and no one developing while this change is made, checked, and then pushed into main before dev could happen again. Maybe something for the main dev team to work on between quarter legacy sprints.
